Repository zoo-labs/zoo, pull requests merged in 2021-07, with the labels that each got.

#22 Add `ZooAuction` contracts and tests
  LICENSE
  package.json
  packages/contracts/src/AuctionHouse.sol
  packages/contracts/src/Market.sol
  packages/contracts/src/Media.sol
  packages/contracts/src/ZooAuction.sol
  packages/contracts/src/interfaces/IAuctionHouse.sol
  packages/contracts/src/interfaces/IMarket.sol
  packages/contracts/src/interfaces/IMedia.sol
  packages/contracts/src/test/BadBidder.sol
  packages/contracts/src/test/BadERC721.sol
  packages/contracts/src/test/TestERC721.sol
  packages/contracts/src/test/WETH.sol
  packages/contracts/test/ZooAuction.test.ts
  packages/contracts/test/ZooToken.test.ts
  packages/contracts/test/integration.test.ts
  packages/contracts/test/utils.ts
Labels: contracts

#29 Add `ZooAuction` contract to manage auction logic
  LICENSE
  package.json
  packages/contracts/src/AuctionHouse.sol
  packages/contracts/src/Decimal.sol
  packages/contracts/src/ERC721.sol
  packages/contracts/src/ERC721Burnable.sol
  packages/contracts/src/Market.sol
  packages/contracts/src/Math.sol
  packages/contracts/src/Media.sol
  packages/contracts/src/ZooAuction.sol
  packages/contracts/src/ZooDrop.sol
  packages/contracts/src/ZooMarket.sol
  packages/contracts/src/ZooMedia.sol
  packages/contracts/src/ZooToken.sol
  packages/contracts/src/interfaces/IAuctionHouse.sol
  packages/contracts/src/interfaces/IMarket.sol
  packages/contracts/src/interfaces/IMedia.sol
  packages/contracts/src/test/BadBidder.sol
  packages/contracts/src/test/BadERC721.sol
  packages/contracts/src/test/TestERC721.sol
  packages/contracts/src/test/WETH.sol
  packages/contracts/test/ZooAuction.test.ts
  packages/contracts/test/ZooToken.test.ts
  packages/contracts/test/integration.test.ts
  packages/contracts/test/utils.ts
Labels: contracts

#47 Feature: Zoo Redux
  packages/app/src/entities/zooentities.ts
  packages/app/src/state/actions.ts
  packages/app/src/state/eggs/index.ts
  packages/app/src/state/index.tsx
  packages/app/src/state/types.ts
  packages/app/src/state/zoo/index.ts
  packages/app/src/state/zoo/test.ts
Labels: enhancement

#48 Bugfix: Modal Color Adjustment
  packages/app/src/components/Button/theme.ts
  packages/app/src/components/Modal/styles.tsx
  packages/app/src/components/WalletModal/AccountModal.tsx
Labels: bug

#49 Bugfix: Overflowing Logo
  packages/app/src/components/SideMenu/Menu.tsx
Labels: bug

#113 Egg Icon Home Button on Feed Cards
  packages/app/src/components/Card/SwipeCard.tsx
  packages/app/src/components/SideMenu/components/ZooHomeButton.tsx
  packages/app/src/media/ZooEggLogoWhite.png
  packages/app/src/media/ZooEggWhite.png
  packages/app/src/views/Feed.tsx
  packages/app/src/views/FeedCard.tsx
Labels: enhancement, frontend

#132 Remove Critical Warning Issues
  packages/app/src/components/BuyEggs/BuyEggs.tsx
  packages/app/src/components/SideMenu/components/PanelBody.tsx
  packages/app/src/views/Feed.tsx
  packages/app/src/views/MyZooAccount.tsx
Labels: bug
